### ISSUE TITLE
Clicking submit input in form does not cause form submission

### ISSUE THREAD

**Issue by mpearce-cafepress** [thatcher/env-js#1]
<p>Below is an example Rhino session showing the problem.  Notice that the &quot;submit&quot; function call causes a print statement and the input click does not.</p>

<p>Example HTML file (form.html):<br />----------------------------------------------------------------------<br />&lt;html&gt;<br />&lt;body&gt;<br />&lt;form&gt;<br />&lt;input type=&quot;submit&quot; /&gt;<br />&lt;/form&gt;<br />&lt;/body&gt;<br />&lt;/html&gt;</p>

<p>Rhino Session:<br />----------------------------------------------------------------------<br />js&gt; load('lib/env.rhino.js')<br />js&gt; load('lib/jquery-1.3.2.js')<br />js&gt; window.location = 'form.html'<br />form.html<br />js&gt; $('body').size();<br />1<br />js&gt; $('form').submit(function() { print('submitted!'); });<br />[object Object]<br />js&gt; $('form').submit();<br />submitted!<br />[object Object]<br />js&gt; $('input').click();<br />[object Object]<br />js&gt; <br /></p>

**Comment by thatcher** [comment]
this has a ticket in http://envjs.lighthouseapp.com/
