### ISSUE TITLE
Download links on http://env-js.appspot.com/release/1.0.x are broken

### ISSUE THREAD

**Issue by dwt** [thatcher/env-js#3]
They all point to nonexisting places on github.

**Comment by thatcher** [comment]
could you add a ticket at http://envjs.lighthouseapp.com/ ? we recently remove build artifacts from commits to make changesets more readable and the result is the latest build isnt available via git without building it yourself.  I need to update the site (badly) anyway and this might get me to finally do it.

Thanks for finding this!
Thatcher

**Comment by dwt** [comment]
ported
