### ISSUE TITLE
events: differences between "interface" names and "feature" names

### ISSUE THREAD

**Issue by dperini** [thatcher/env-js#4]
I believe all event interfaces does not end with the letter "s", seems to me those are features names. It is "MouseEvent" and not "MouseEvents", "Event" and not "Events". Though some browser accepts both syntaxes for some of them, but only the first is the correct one as for specifications.

```
document.createEvent("Event");
document.implementation.hasFeature("Events", "");

document.createEvent("MouseEvent");
document.implementation.hasFeature("MouseEvents", "");
```

Thank you for the great work and the details you have put in it.

**Comment by thatcher** [comment]
could you create a ticket in http://envjs.lighthouseapp.com/ ? thanks!
