### ISSUE TITLE
print(JSON.stringify({re:/[a-z]/})); shows empty object 

### ISSUE THREAD

**Issue by sombriks** [thatcher/env-js#48]
using env.rhino.1.2.js here

**Comment by morganrallen** [comment]
RegExp is not encodable as anything else. It is in fact an object and has no enumerable properties.

```
var re = /[a-z]/;
console.log(typeof re); // "object"
for(var property in re) console.log(property); // nothing
```

**Comment by sombriks** [comment]
Hi,
indeed it prints out nothing. For my purposes i should store the source string.

https://developer.mozilla.org/en/JavaScript/Guide/Regular_Expressions#Working_with_Regular_Expressions

according to it (and tested) regex have attributes but for some reason they doesn't iterate

**Comment by morganrallen** [comment]
Don't know what to tell you. It just single does not work. JSON treats it as an object and none of the properties are enumerable (meaning for(i in obj) does not see them). Every implementation of JSON will give you the same result. Your best bet would be storing the regexp as a string and somewhere in your application use `new RegExp(reString)`

**Comment by sombriks** [comment]
indeed, the best option is to store the string instead the literal regex
